name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Unit Test
      run: make test
